### ISSUE TITLE
New measure entry error

### ISSUE THREAD

**Issue by StevenCaddy** [underwatergrasshopper/poe_exp_after_dot#44]
![Screenshot (1)](https://github.com/underwatergrasshopper/poe_exp_after_dot/assets/25208469/093cef96-1a64-43ff-8944-8c0d09af7c88)

When clicking on the exp bar it doesn't add the new entry even with the in game tool tip showing

**Comment by underwatergrasshopper** [comment]
In menu there is option `Open Data Folder`. Can you show me content of `runtime.log`?

**Comment by StevenCaddy** [comment]
[runtime.log](https://github.com/underwatergrasshopper/poe_exp_after_dot/files/14105291/runtime.log)
resolution is 2560x1440 and it is the same with game and app

**Comment by underwatergrasshopper** [comment]
I saw screenshot is in 2544x1436 resolution. 
Is this screenshot was cut?

**Comment by StevenCaddy** [comment]
Yes just cut out second monitor

**Comment by underwatergrasshopper** [comment]
Ok. Unfull resolution affects scanning region and it cuts out part of text from tooltip.

Add to `settings.json` in `Data Folder` this section under `"layouts"`:
```json
"close_to_2560x1440": {
    "info_board_x": 734,
    "info_board_bottom": 1409,
    "control_region_x": 734,
    "control_region_y": 1412,
    "control_region_width": 1092,
    "control_region_height": 28,
    "in_game_exp_bar_x": 734,
    "in_game_exp_bar_y": 1422,
    "in_game_exp_bar_width": 1092,
    "in_game_exp_bar_height": 8,
    "in_game_exp_tooltip_x_offset": 64,
    "in_game_exp_tooltip_y": 1339,
    "in_game_exp_tooltip_width": 603,
    "in_game_exp_tooltip_height": 101
},
``` 
Then From menu `Layout` > `close_to_2560x1440`.
And uncheck `detect on start`.

Should work.

**Comment by underwatergrasshopper** [comment]
If this doesn't work. Try do second screenshot when you point cursor exactly at 50% marker in exp bar.

It looks like, something is wrong with detection box for text.

**Comment by underwatergrasshopper** [comment]
Try with this in `"layouts"` section in settings.

```
"half_x_offset_2560x1440": {
    "info_board_x": 734,
    "info_board_bottom": 1409,
    "control_region_x": 734,
    "control_region_y": 1412,
    "control_region_width": 1092,
    "control_region_height": 28,
    "in_game_exp_bar_x": 734,
    "in_game_exp_bar_y": 1422,
    "in_game_exp_bar_width": 1092,
    "in_game_exp_bar_height": 8,
    "in_game_exp_tooltip_x_offset": 32,
    "in_game_exp_tooltip_y": 1343,
    "in_game_exp_tooltip_width": 587,
    "in_game_exp_tooltip_height": 97
},    
```

**Comment by StevenCaddy** [comment]
![Screenshot (5)](https://github.com/underwatergrasshopper/poe_exp_after_dot/assets/25208469/430303dc-9d14-40a5-a6b8-61edc8b45154)
That worked!

Thank you so much. Sorry for how much of a pain that was.

**Comment by underwatergrasshopper** [comment]
It's fine. For some reason offset between cursor and in-game exp tooltip is half of it's supposed normal length. Hard to tell why. Might be existence of second monitor making game to do this. But this new settings should work for your setup now :)
