### ISSUE TITLE
LVL1 entry only

### ISSUE THREAD

**Issue by LostRosuto** [underwatergrasshopper/poe_exp_after_dot#49]
[runtime.log](https://github.com/underwatergrasshopper/poe_exp_after_dot/files/14158943/runtime.log)

On 0.1.4 it correctly reads text but every entry is empty LVL1 exp=2
On 0.1.4rc2 it has critical error

I tried to uninstall and install again both tool and python. Don't know what I'm missing.

**Comment by underwatergrasshopper** [comment]
Hi.

Try using version 0.1.4, but without debug mode, it's bugged.

Statistics are computed per level, so when you gain a level and you do first measurement for this level you will always have "zeroed" entry with "never"s.

**Comment by underwatergrasshopper** [comment]
> I never had custom font. I play standalone version in English. I tried to reinstall Fontin now but it didn't help. Language change also didn't help. What can I try to fix this? Game reinstall? Delete some fonts?

There is no need for that. Game probably gets language local settings from your system.

Could you try this version. Tell after how often gives you actual entry.
[poe_exp_after_dot-0.1.5.dev2-py3-none-win_amd64.whl.zip](https://github.com/underwatergrasshopper/poe_exp_after_dot/files/14168853/poe_exp_after_dot-0.1.5.dev2-py3-none-win_amd64.whl.zip)

**Comment by LostRosuto** [comment]
![Zrzut ekranu (5)](https://github.com/underwatergrasshopper/poe_exp_after_dot/assets/68561335/c682f364-8615-4237-b64c-e6a7e96a290e)
![Zrzut ekranu (6)](https://github.com/underwatergrasshopper/poe_exp_after_dot/assets/68561335/4973575d-8147-4a20-9b5c-e6b026d86827)
[runtime.log](https://github.com/underwatergrasshopper/poe_exp_after_dot/files/14170732/runtime.log)

Seems that problem is solved now. I tried to measure about 10 times and only once it incorectly put me at level 3 because of reading exp amount too short by three last digit. So I think its normal and works well.

Thank You for the fix and help. Always wanted a tool like this. It's awesome.

**Comment by underwatergrasshopper** [comment]
Soon I will do proper release with this fix.

**Comment by underwatergrasshopper** [comment]
Fix applied to [v0.1.5](https://github.com/underwatergrasshopper/poe_exp_after_dot/releases/tag/v0.1.5).
