### ISSUE TITLE
In game SPACE separators sometimes too small

### ISSUE THREAD

**Issue by LostRosuto** [underwatergrasshopper/poe_exp_after_dot#50]
When using SPACE as a thousand separator some number combinations cause space between thousands to shrink. Example: 3 684 45**13**36 -> 1 and then 3 produce smaller space than normal. Tool can't recognize smaller spaces as SPACE separator every single time when this happens. I solved problem for myself by changing Windows default SPACE separator to DOT separator. Not a huge problem but I wanted to let You know. As always, thanks for this tool.

[runtime.log](https://github.com/underwatergrasshopper/poe_exp_after_dot/files/15179649/runtime.log)

![Zrzut ekranu (8)](https://github.com/underwatergrasshopper/poe_exp_after_dot/assets/68561335/be017355-38d4-463a-8b4b-d9967bd34670)
![Zrzut ekranu (9)](https://github.com/underwatergrasshopper/poe_exp_after_dot/assets/68561335/1272eb30-7c0f-4aca-b40a-80ba398ca25b)
![Zrzut ekranu (10)](https://github.com/underwatergrasshopper/poe_exp_after_dot/assets/68561335/44baa163-36ba-48fc-b5a6-f49cde1d3e0e)

**Comment by underwatergrasshopper** [comment]
Is this issue was occurring with previous versions as often?

**Comment by underwatergrasshopper** [comment]
I've changed reading of current exp value, to be more forgiving with missing spaces when thousands separator is space. Number of digits still needs to be in correct range. This should reduce misreads.

Link version with changes: [poe_exp_after_dot v0.2.1](https://github.com/underwatergrasshopper/poe_exp_after_dot/releases/tag/v0.2.1)

**Comment by LostRosuto** [comment]
Last league I couldn't push to 100 unfortunately so I didn't use tool as often. Don't remember to have this bug then.
I just tested new version on few maps. Then tried to replicate XX1 3XX and XX4 4XX on the exp bar. Problem is gone. Very rarely there is ERR as always but LVL3 incorrect read did not happen once. If bug still exist it must be very rare. Thanks for helping with a problem.
I'm going to play poe now for few hours and update this post after that.

[runtime.log](https://github.com/underwatergrasshopper/poe_exp_after_dot/files/15198824/runtime.log)

![Zrzut ekranu (11)](https://github.com/underwatergrasshopper/poe_exp_after_dot/assets/68561335/b0900549-e0eb-4e83-aff0-fb6d74b88beb)

**Comment by underwatergrasshopper** [comment]
From your `runtime.log` I've realized that, there is another bug which causes misreads.
Version from below have a fix for that too.

[poe_exp_after_dot v0.2.2](https://github.com/underwatergrasshopper/poe_exp_after_dot/releases/tag/v0.2.2)

**Comment by LostRosuto** [comment]
Glad to hear it helped. After few hours I can confirm info from my previous post. ERR misreads were pretty rare for me. Next time I will check out new version as always. Thanks once more for help.
